// ── Centralized API Layer ────────────────────────────────────────────────────
// All data access functions in one place.
// Pages should import from here instead of using Supabase directly.
//
// Usage:
//   import { loadProjects, loadTaskStates } from '@/lib/api'

export { loadProjects, loadTaskStates, loadProjectFunding, updateProject, loadUsers, loadProjectById, loadProjectsByIds, searchProjects } from './projects'
export type { ProjectQuery } from './projects'
export { loadProjectNotes, loadTaskNotes, addNote, deleteNote, createMentionNotification } from './notes'
export { upsertTaskState, loadTaskHistory, insertTaskHistory, loadProjectAdders, addProjectAdder, deleteProjectAdder } from './tasks'
export { loadScheduleByDateRange } from './schedules'
export { loadChangeOrders } from './change-orders'
export { loadCrewsByIds, loadActiveCrews } from './crews'
export { loadProjectFiles, searchProjectFiles, searchAllProjectFiles, loadAllProjectFiles, loadDocumentRequirements, loadProjectDocuments, updateDocumentStatus } from './documents'
export type { ProjectFile, DocumentRequirement, ProjectDocument } from './documents'
export { loadEquipment, searchEquipment, loadAllEquipment, stripRawPrice } from './equipment'
export type { Equipment, EquipmentCategory } from './equipment'
export { EQUIPMENT_CATEGORIES } from './equipment'
export { loadProjectMaterials, addProjectMaterial, updateProjectMaterial, deleteProjectMaterial, autoGenerateMaterials, loadWarehouseStock, loadAllProjectMaterials, MATERIAL_STATUSES, MATERIAL_SOURCES, MATERIAL_CATEGORIES } from './inventory'
export type { ProjectMaterial, WarehouseStock, MaterialStatus, MaterialSource, MaterialCategory } from './inventory'
export { sendToEdge, syncProjectToEdge, syncFundingToEdge, isEdgeConfigured, getEdgeWebhookUrl } from './edge-sync'
export type { EdgeEventType, EdgeWebhookPayload } from './edge-sync'
export { loadVendors, searchVendors, loadVendor, addVendor, updateVendor, deleteVendor, VENDOR_CATEGORIES, EQUIPMENT_TYPE_OPTIONS } from './vendors'
export type { Vendor, VendorCategory } from './vendors'
export { loadWorkOrders, loadWorkOrder, createWorkOrder, updateWorkOrder, updateWorkOrderStatus, addChecklistItem, toggleChecklistItem, deleteChecklistItem, createWorkOrderFromProject, loadProjectWorkOrders, generateWONumber, getValidTransitions, WO_CHECKLIST_TEMPLATES } from './work-orders'
export type { WorkOrder, WOChecklistItem, WorkOrderFilters } from './work-orders'
export { loadProjectWarranties, addWarranty, updateWarranty, deleteWarranty, loadWarrantyClaims, addClaim, updateClaim, loadExpiringWarranties, loadAllWarranties, loadOpenClaims, WARRANTY_EQUIPMENT_TYPES, CLAIM_STATUSES } from './warranties'
export type { EquipmentWarranty, WarrantyClaim, WarrantyFilters, WarrantyEquipmentType, ClaimStatus } from './warranties'
export { loadVehicles, loadVehicle, addVehicle, updateVehicle, deleteVehicle, loadVehicleMaintenance, addMaintenance, updateMaintenance, loadUpcomingMaintenance, VEHICLE_STATUSES, MAINTENANCE_TYPES, MAINTENANCE_TYPE_LABELS, STATUS_LABELS as VEHICLE_STATUS_LABELS } from './fleet'
export type { Vehicle, MaintenanceRecord, VehicleStatus, MaintenanceType, VehicleFilters } from './fleet'
export { loadFieldDefinitions, addFieldDefinition, updateFieldDefinition, deleteFieldDefinition, loadProjectCustomFields, saveProjectCustomField, loadAllCustomFieldValues, FIELD_TYPES } from './custom-fields'
export type { CustomFieldDefinition, CustomFieldValue, CustomFieldType } from './custom-fields'
export { loadCalendarSettings, updateCalendarSettings, loadSyncStatus, upsertSyncEntry, deleteSyncEntry, loadRecentSyncEntries, isCalendarConfigured, JOB_TYPE_COLOR_ID } from './calendar'
export type { CalendarSettings, CalendarSyncEntry, CalendarEvent } from './calendar'
export { loadNTPRequests, loadNTPRequestByProject, loadNTPHistory, submitNTPRequest, reviewNTPRequest, loadNTPQueue, resubmitNTPRequest, NTP_STATUSES, NTP_STATUS_LABELS, NTP_STATUS_BADGE } from './ntp'
export type { NTPRequest, NTPStatus } from './ntp'
export { loadAssignments, loadAssignmentByProject, loadAssignmentHistory, submitAssignment, updateAssignmentStatus, addDeliverable, loadAssignmentQueue, ASSIGNMENT_TYPES, ASSIGNMENT_STATUSES, ASSIGNMENT_STATUS_LABELS, ASSIGNMENT_STATUS_BADGE, ASSIGNMENT_TYPE_LABELS } from './engineering'
export type { EngineeringAssignment, AssignmentStatus, AssignmentType } from './engineering'
export { loadEngineeringConfig, updateEngineeringConfig, autoRouteAssignment } from './engineering-config'
export type { EngineeringConfig } from './engineering-config'
export { generateInvoiceNumber, loadInvoices, loadInvoice, loadProjectInvoices, createInvoice, updateInvoiceStatus, addLineItem, deleteLineItem, getValidInvoiceTransitions, loadInvoiceRules, addInvoiceRule, updateInvoiceRule, deleteInvoiceRule, INVOICE_STATUSES, INVOICE_STATUS_LABELS, INVOICE_STATUS_BADGE, MILESTONE_LABELS } from './invoices'
export type { Invoice, InvoiceLineItem, InvoiceStatus, InvoiceRule } from './invoices'
export { loadCommissionRates, addCommissionRate, updateCommissionRate, deleteCommissionRate, calculateCommission, loadCommissionRecords, createCommissionRecord, updateCommissionRecord, loadEarningsSummary, generateProjectCommissions, loadCommissionTiers, addCommissionTier, deleteCommissionTier, loadGeoModifiers, addGeoModifier, updateGeoModifier, deleteGeoModifier, loadHierarchy, addHierarchyMember, updateHierarchyMember, removeHierarchyMember, getTieredRate, getGeoModifier, calculateTieredCommission, COMMISSION_STATUSES, COMMISSION_STATUS_LABELS, COMMISSION_STATUS_BADGE, DEFAULT_ROLES } from './commissions'
export type { CommissionRate, CommissionRecord, CommissionStatus, CommissionRateType, CommissionTier, CommissionGeoModifier, CommissionHierarchy, CommissionBreakdown, CommissionRecordFilters, EarningsSummary } from './commissions'
export { loadPayScales, addPayScale, updatePayScale, deletePayScale, loadPayDistribution, updatePayDistribution, addPayDistribution, deletePayDistribution, loadSalesTeams, addSalesTeam, updateSalesTeam, deleteSalesTeam, loadSalesReps, addSalesRep, updateSalesRep, loadRepById, loadOnboardingRequirements, loadRepDocuments, updateOnboardingDocStatus, initializeRepDocuments, calculateOverride, calculateSplitOverride, calculateTeamDistribution, REP_STATUSES, REP_STATUS_LABELS, REP_STATUS_BADGE, DOC_STATUSES, DOC_STATUS_LABELS, DOC_STATUS_BADGE, DEFAULT_ROLE_KEYS } from './sales-teams'
export type { PayScale, PayDistribution, SalesTeam, SalesRep, OnboardingRequirement, OnboardingDocument, RepStatus, OnboardingDocStatus, SalesRepFilters, OverrideBreakdown, DistributionLine } from './sales-teams'
